// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="GOST_Encrypt_SR_GOST_Encrypt_SR,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.183000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=692,HLS_SYN_LUT=1397,HLS_VERSION=2021_1}" *)

module GOST_Encrypt_SR (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Data_i,
        Data_o,
        Data_o_ap_vld,
        Size,
        Mode,
        GOST_Table,
        GOST_Key
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] Data_i;
output  [7:0] Data_o;
output   Data_o_ap_vld;
input  [31:0] Size;
input   Mode;
input  [7:0] GOST_Table;
input  [7:0] GOST_Key;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] Data_o;
reg Data_o_ap_vld;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] grp_GOST_Crypt_Step_fu_193_ap_return;
wire    ap_CS_fsm_state10;
wire   [0:0] Mode_read_read_fu_124_p2;
wire   [3:0] Cur_Part_Size_fu_256_p3;
reg   [3:0] Cur_Part_Size_reg_555;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln167_fu_230_p2;
wire   [63:0] Data_prep_fu_342_p9;
reg   [63:0] Data_prep_reg_567;
wire    ap_CS_fsm_state4;
wire   [63:0] Data_prep_3_fu_471_p9;
reg   [63:0] Data_prep_3_reg_582;
wire    ap_CS_fsm_state16;
wire    grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_start;
wire    grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_done;
wire    grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_idle;
wire    grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_ready;
wire   [63:0] grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out;
wire    grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out_ap_vld;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_start;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_done;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_idle;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_ready;
wire   [63:0] grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_Data_prep_330_out;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_Data_prep_330_out_ap_vld;
wire   [63:0] grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din1;
wire   [7:0] grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din2;
wire  signed [0:0] grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din3;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_start;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_done;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_idle;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_ready;
wire   [63:0] grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_128_out;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_128_out_ap_vld;
wire   [63:0] grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_4_GOST_Crypt_Step_fu_587_p_din1;
wire   [7:0] grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_4_GOST_Crypt_Step_fu_587_p_din2;
wire   [0:0] grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_4_GOST_Crypt_Step_fu_587_p_din3;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_start;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_done;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_idle;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_ready;
wire   [63:0] grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_Data_prep_5_out;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_Data_prep_5_out_ap_vld;
wire   [63:0] grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din1;
wire   [7:0] grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din2;
wire  signed [0:0] grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din3;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_start;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_done;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_idle;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_ready;
wire   [63:0] grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_Data_prep_6_out;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_Data_prep_6_out_ap_vld;
wire   [63:0] grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din1;
wire   [7:0] grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din2;
wire  signed [0:0] grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din3;
wire    grp_GOST_Crypt_Step_fu_193_ap_ready;
reg   [63:0] grp_GOST_Crypt_Step_fu_193_Data_prep_read;
reg   [7:0] grp_GOST_Crypt_Step_fu_193_p_read1;
reg   [0:0] grp_GOST_Crypt_Step_fu_193_Last;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_start;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_done;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_idle;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_ready;
wire   [63:0] grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_Data_prep_229_out;
wire    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_Data_prep_229_out_ap_vld;
wire   [63:0] grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din1;
wire   [7:0] grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din2;
wire  signed [0:0] grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din3;
wire    grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_start;
wire    grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_done;
wire    grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_idle;
wire    grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_ready;
wire   [7:0] grp_GOST_Encrypt_SR_Pipeline_7_fu_208_Data;
wire    grp_GOST_Encrypt_SR_Pipeline_7_fu_208_Data_ap_vld;
wire    Data_prep_4_GOST_Crypt_Step_fu_587_ap_ready;
wire   [63:0] Data_prep_4_GOST_Crypt_Step_fu_587_ap_return;
reg   [63:0] Data_prep_7_reg_148;
reg    grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_start_reg;
wire    ap_CS_fsm_state11;
reg    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_start_reg;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
reg    grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_start_reg;
wire    ap_CS_fsm_state17;
reg   [31:0] Size_assign_fu_96;
wire   [31:0] sub_ln189_fu_383_p2;
wire   [28:0] tmp_fu_236_p4;
wire   [0:0] icmp_ln169_fu_246_p2;
wire   [3:0] trunc_ln169_fu_252_p1;
wire   [7:0] p_s_fu_302_p4;
wire   [7:0] p_5_fu_322_p4;
wire   [7:0] p_6_fu_332_p4;
wire   [7:0] p_4_fu_312_p4;
wire   [7:0] empty_fu_268_p1;
wire   [7:0] p_1_fu_282_p4;
wire   [7:0] p_2_fu_292_p4;
wire   [7:0] p_3_fu_272_p4;
wire   [31:0] zext_ln188_fu_380_p1;
wire   [7:0] p_10_fu_431_p4;
wire   [7:0] p_12_fu_451_p4;
wire   [7:0] p_13_fu_461_p4;
wire   [7:0] p_11_fu_441_p4;
wire   [7:0] empty_108_fu_397_p1;
wire   [7:0] p_9_fu_411_p4;
wire   [7:0] p_7_fu_421_p4;
wire   [7:0] p_8_fu_401_p4;
reg   [16:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_start_reg = 1'b0;
#0 grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_start_reg = 1'b0;
#0 grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_start_reg = 1'b0;
#0 grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_start_reg = 1'b0;
#0 grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_start_reg = 1'b0;
#0 grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_start_reg = 1'b0;
#0 grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_start_reg = 1'b0;
end

GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_1 grp_GOST_Encrypt_SR_Pipeline_1_fu_157(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_start),
    .ap_done(grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_done),
    .ap_idle(grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_idle),
    .ap_ready(grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_ready),
    .Cur_Part_Size(Cur_Part_Size_reg_555),
    .Data_load_cast(Data_i),
    .p_out(grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out),
    .p_out_ap_vld(grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out_ap_vld)
);

GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1 grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_start),
    .ap_done(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_done),
    .ap_idle(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_idle),
    .ap_ready(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_ready),
    .Data_prep(Data_prep_reg_567),
    .GOST_Table_load(GOST_Table),
    .Data_prep_330_out(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_Data_prep_330_out),
    .Data_prep_330_out_ap_vld(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_Data_prep_330_out_ap_vld),
    .grp_GOST_Crypt_Step_fu_193_p_din1(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din1),
    .grp_GOST_Crypt_Step_fu_193_p_din2(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din2),
    .grp_GOST_Crypt_Step_fu_193_p_din3(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din3),
    .grp_GOST_Crypt_Step_fu_193_p_dout0(grp_GOST_Crypt_Step_fu_193_ap_return),
    .grp_GOST_Crypt_Step_fu_193_p_ready(grp_GOST_Crypt_Step_fu_193_ap_ready)
);

GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2 grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_start),
    .ap_done(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_done),
    .ap_idle(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_idle),
    .ap_ready(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_ready),
    .Data_prep(Data_prep_reg_567),
    .GOST_Table_load(GOST_Table),
    .Data_prep_128_out(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_128_out),
    .Data_prep_128_out_ap_vld(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_128_out_ap_vld),
    .Data_prep_4_GOST_Crypt_Step_fu_587_p_din1(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_4_GOST_Crypt_Step_fu_587_p_din1),
    .Data_prep_4_GOST_Crypt_Step_fu_587_p_din2(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_4_GOST_Crypt_Step_fu_587_p_din2),
    .Data_prep_4_GOST_Crypt_Step_fu_587_p_din3(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_4_GOST_Crypt_Step_fu_587_p_din3),
    .Data_prep_4_GOST_Crypt_Step_fu_587_p_dout0(Data_prep_4_GOST_Crypt_Step_fu_587_ap_return),
    .Data_prep_4_GOST_Crypt_Step_fu_587_p_ready(Data_prep_4_GOST_Crypt_Step_fu_587_ap_ready)
);

GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3 grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_start),
    .ap_done(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_done),
    .ap_idle(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_idle),
    .ap_ready(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_ready),
    .Data_prep_330_reload(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_Data_prep_330_out),
    .GOST_Table_load(GOST_Table),
    .Data_prep_5_out(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_Data_prep_5_out),
    .Data_prep_5_out_ap_vld(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_Data_prep_5_out_ap_vld),
    .grp_GOST_Crypt_Step_fu_193_p_din1(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din1),
    .grp_GOST_Crypt_Step_fu_193_p_din2(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din2),
    .grp_GOST_Crypt_Step_fu_193_p_din3(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din3),
    .grp_GOST_Crypt_Step_fu_193_p_dout0(grp_GOST_Crypt_Step_fu_193_ap_return),
    .grp_GOST_Crypt_Step_fu_193_p_ready(grp_GOST_Crypt_Step_fu_193_ap_ready)
);

GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4 grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_start),
    .ap_done(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_done),
    .ap_idle(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_idle),
    .ap_ready(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_ready),
    .Data_prep_5_reload(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_Data_prep_5_out),
    .GOST_Table_load(GOST_Table),
    .Data_prep_6_out(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_Data_prep_6_out),
    .Data_prep_6_out_ap_vld(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_Data_prep_6_out_ap_vld),
    .grp_GOST_Crypt_Step_fu_193_p_din1(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din1),
    .grp_GOST_Crypt_Step_fu_193_p_din2(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din2),
    .grp_GOST_Crypt_Step_fu_193_p_din3(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din3),
    .grp_GOST_Crypt_Step_fu_193_p_dout0(grp_GOST_Crypt_Step_fu_193_ap_return),
    .grp_GOST_Crypt_Step_fu_193_p_ready(grp_GOST_Crypt_Step_fu_193_ap_ready)
);

GOST_Encrypt_SR_GOST_Crypt_Step grp_GOST_Crypt_Step_fu_193(
    .ap_ready(grp_GOST_Crypt_Step_fu_193_ap_ready),
    .Data_prep_read(grp_GOST_Crypt_Step_fu_193_Data_prep_read),
    .p_read1(grp_GOST_Crypt_Step_fu_193_p_read1),
    .Last(grp_GOST_Crypt_Step_fu_193_Last),
    .ap_return(grp_GOST_Crypt_Step_fu_193_ap_return)
);

GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3 grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_start),
    .ap_done(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_done),
    .ap_idle(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_idle),
    .ap_ready(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_ready),
    .Data_prep_128_reload(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_128_out),
    .GOST_Table_load(GOST_Table),
    .Data_prep_229_out(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_Data_prep_229_out),
    .Data_prep_229_out_ap_vld(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_Data_prep_229_out_ap_vld),
    .grp_GOST_Crypt_Step_fu_193_p_din1(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din1),
    .grp_GOST_Crypt_Step_fu_193_p_din2(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din2),
    .grp_GOST_Crypt_Step_fu_193_p_din3(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din3),
    .grp_GOST_Crypt_Step_fu_193_p_dout0(grp_GOST_Crypt_Step_fu_193_ap_return),
    .grp_GOST_Crypt_Step_fu_193_p_ready(grp_GOST_Crypt_Step_fu_193_ap_ready)
);

GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_7 grp_GOST_Encrypt_SR_Pipeline_7_fu_208(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_start),
    .ap_done(grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_done),
    .ap_idle(grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_idle),
    .ap_ready(grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_ready),
    .Cur_Part_Size(Cur_Part_Size_reg_555),
    .Data_prep_3(Data_prep_3_reg_582),
    .Data(grp_GOST_Encrypt_SR_Pipeline_7_fu_208_Data),
    .Data_ap_vld(grp_GOST_Encrypt_SR_Pipeline_7_fu_208_Data_ap_vld)
);

GOST_Encrypt_SR_GOST_Crypt_Step Data_prep_4_GOST_Crypt_Step_fu_587(
    .ap_ready(Data_prep_4_GOST_Crypt_Step_fu_587_ap_ready),
    .Data_prep_read(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_4_GOST_Crypt_Step_fu_587_p_din1),
    .p_read1(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_4_GOST_Crypt_Step_fu_587_p_din2),
    .Last(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_4_GOST_Crypt_Step_fu_587_p_din3),
    .ap_return(Data_prep_4_GOST_Crypt_Step_fu_587_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln167_fu_230_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_start_reg <= 1'b1;
        end else if ((grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_ready == 1'b1)) begin
            grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_start_reg <= 1'b1;
        end else if ((grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_ready == 1'b1)) begin
            grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_start_reg <= 1'b1;
        end else if ((grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_ready == 1'b1)) begin
            grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_start_reg <= 1'b0;
    end else begin
        if (((1'd1 == Mode_read_read_fu_124_p2) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_start_reg <= 1'b1;
        end else if ((grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_ready == 1'b1)) begin
            grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_start_reg <= 1'b1;
        end else if ((grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_ready == 1'b1)) begin
            grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_start_reg <= 1'b0;
    end else begin
        if (((1'd0 == Mode_read_read_fu_124_p2) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_start_reg <= 1'b1;
        end else if ((grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_ready == 1'b1)) begin
            grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_start_reg <= 1'b1;
        end else if ((grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_ready == 1'b1)) begin
            grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        Size_assign_fu_96 <= Size;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        Size_assign_fu_96 <= sub_ln189_fu_383_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln167_fu_230_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        Cur_Part_Size_reg_555 <= Cur_Part_Size_fu_256_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        Data_prep_3_reg_582 <= Data_prep_3_fu_471_p9;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'd1 == Mode_read_read_fu_124_p2) & (1'b1 == ap_CS_fsm_state10)) | ((1'd0 == Mode_read_read_fu_124_p2) & (1'b1 == ap_CS_fsm_state10)))) begin
        Data_prep_7_reg_148 <= grp_GOST_Crypt_Step_fu_193_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        Data_prep_reg_567 <= Data_prep_fu_342_p9;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (grp_GOST_Encrypt_SR_Pipeline_7_fu_208_Data_ap_vld == 1'b1))) begin
        Data_o = grp_GOST_Encrypt_SR_Pipeline_7_fu_208_Data;
    end else begin
        Data_o = Data_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        Data_o_ap_vld = grp_GOST_Encrypt_SR_Pipeline_7_fu_208_Data_ap_vld;
    end else begin
        Data_o_ap_vld = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_230_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_230_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_GOST_Crypt_Step_fu_193_Data_prep_read = grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        grp_GOST_Crypt_Step_fu_193_Data_prep_read = grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        grp_GOST_Crypt_Step_fu_193_Data_prep_read = grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state5))) begin
        grp_GOST_Crypt_Step_fu_193_Data_prep_read = grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din1;
    end else if (((1'd1 == Mode_read_read_fu_124_p2) & (1'b1 == ap_CS_fsm_state10))) begin
        grp_GOST_Crypt_Step_fu_193_Data_prep_read = grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_Data_prep_229_out;
    end else if (((1'd0 == Mode_read_read_fu_124_p2) & (1'b1 == ap_CS_fsm_state10))) begin
        grp_GOST_Crypt_Step_fu_193_Data_prep_read = grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_Data_prep_6_out;
    end else begin
        grp_GOST_Crypt_Step_fu_193_Data_prep_read = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_GOST_Crypt_Step_fu_193_Last = grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din3;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        grp_GOST_Crypt_Step_fu_193_Last = grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din3;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        grp_GOST_Crypt_Step_fu_193_Last = grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din3;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state5))) begin
        grp_GOST_Crypt_Step_fu_193_Last = grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din3;
    end else if ((((1'd1 == Mode_read_read_fu_124_p2) & (1'b1 == ap_CS_fsm_state10)) | ((1'd0 == Mode_read_read_fu_124_p2) & (1'b1 == ap_CS_fsm_state10)))) begin
        grp_GOST_Crypt_Step_fu_193_Last = 1'd1;
    end else begin
        grp_GOST_Crypt_Step_fu_193_Last = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_GOST_Crypt_Step_fu_193_p_read1 = grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din2;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        grp_GOST_Crypt_Step_fu_193_p_read1 = grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din2;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        grp_GOST_Crypt_Step_fu_193_p_read1 = grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din2;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state5))) begin
        grp_GOST_Crypt_Step_fu_193_p_read1 = grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din2;
    end else if ((((1'd1 == Mode_read_read_fu_124_p2) & (1'b1 == ap_CS_fsm_state10)) | ((1'd0 == Mode_read_read_fu_124_p2) & (1'b1 == ap_CS_fsm_state10)))) begin
        grp_GOST_Crypt_Step_fu_193_p_read1 = GOST_Table;
    end else begin
        grp_GOST_Crypt_Step_fu_193_p_read1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln167_fu_230_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'd1 == Mode_read_read_fu_124_p2) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((1'b1 == ap_CS_fsm_state17) & (grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Cur_Part_Size_fu_256_p3 = ((icmp_ln169_fu_246_p2[0:0] == 1'b1) ? trunc_ln169_fu_252_p1 : 4'd8);

assign Data_prep_3_fu_471_p9 = {{{{{{{{p_10_fu_431_p4}, {p_12_fu_451_p4}}, {p_13_fu_461_p4}}, {p_11_fu_441_p4}}, {empty_108_fu_397_p1}}, {p_9_fu_411_p4}}, {p_7_fu_421_p4}}, {p_8_fu_401_p4}};

assign Data_prep_fu_342_p9 = {{{{{{{{p_s_fu_302_p4}, {p_5_fu_322_p4}}, {p_6_fu_332_p4}}, {p_4_fu_312_p4}}, {empty_fu_268_p1}}, {p_1_fu_282_p4}}, {p_2_fu_292_p4}}, {p_3_fu_272_p4}};

assign Mode_read_read_fu_124_p2 = Mode;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign empty_108_fu_397_p1 = Data_prep_7_reg_148[7:0];

assign empty_fu_268_p1 = grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out[7:0];

assign grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_start = grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_start_reg;

assign grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_start = grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_start_reg;

assign grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_start = grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_start_reg;

assign grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_start = grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_start_reg;

assign grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_start = grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_start_reg;

assign grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_start = grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_start_reg;

assign grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_start = grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_start_reg;

assign icmp_ln167_fu_230_p2 = ((Size_assign_fu_96 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln169_fu_246_p2 = ((tmp_fu_236_p4 == 29'd0) ? 1'b1 : 1'b0);

assign p_10_fu_431_p4 = {{Data_prep_7_reg_148[39:32]}};

assign p_11_fu_441_p4 = {{Data_prep_7_reg_148[63:56]}};

assign p_12_fu_451_p4 = {{Data_prep_7_reg_148[47:40]}};

assign p_13_fu_461_p4 = {{Data_prep_7_reg_148[55:48]}};

assign p_1_fu_282_p4 = {{grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out[15:8]}};

assign p_2_fu_292_p4 = {{grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out[23:16]}};

assign p_3_fu_272_p4 = {{grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out[31:24]}};

assign p_4_fu_312_p4 = {{grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out[63:56]}};

assign p_5_fu_322_p4 = {{grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out[47:40]}};

assign p_6_fu_332_p4 = {{grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out[55:48]}};

assign p_7_fu_421_p4 = {{Data_prep_7_reg_148[23:16]}};

assign p_8_fu_401_p4 = {{Data_prep_7_reg_148[31:24]}};

assign p_9_fu_411_p4 = {{Data_prep_7_reg_148[15:8]}};

assign p_s_fu_302_p4 = {{grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out[39:32]}};

assign sub_ln189_fu_383_p2 = (Size_assign_fu_96 - zext_ln188_fu_380_p1);

assign tmp_fu_236_p4 = {{Size_assign_fu_96[31:3]}};

assign trunc_ln169_fu_252_p1 = Size_assign_fu_96[3:0];

assign zext_ln188_fu_380_p1 = Cur_Part_Size_reg_555;

endmodule //GOST_Encrypt_SR
