-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GOST_Encrypt_SR is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    Data_i : IN STD_LOGIC_VECTOR (7 downto 0);
    Data_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    Data_o_ap_vld : OUT STD_LOGIC;
    Size : IN STD_LOGIC_VECTOR (31 downto 0);
    Mode : IN STD_LOGIC;
    GOST_Table : IN STD_LOGIC_VECTOR (7 downto 0);
    GOST_Key : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of GOST_Encrypt_SR is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "GOST_Encrypt_SR_GOST_Encrypt_SR,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.183000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=692,HLS_SYN_LUT=1397,HLS_VERSION=2021_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (16 downto 0) := "00000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (16 downto 0) := "00000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (16 downto 0) := "00000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (16 downto 0) := "00000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (16 downto 0) := "00000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (16 downto 0) := "00000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (16 downto 0) := "00001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (16 downto 0) := "00010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (16 downto 0) := "00100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (16 downto 0) := "01000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (16 downto 0) := "10000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv29_0 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_GOST_Crypt_Step_fu_193_ap_return : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal Mode_read_read_fu_124_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Cur_Part_Size_fu_256_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal Cur_Part_Size_reg_555 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln167_fu_230_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Data_prep_fu_342_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal Data_prep_reg_567 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal Data_prep_3_fu_471_p9 : STD_LOGIC_VECTOR (63 downto 0);
    signal Data_prep_3_reg_582 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_start : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_done : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_idle : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_ready : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out_ap_vld : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_start : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_done : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_idle : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_ready : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_Data_prep_330_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_Data_prep_330_out_ap_vld : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_start : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_done : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_idle : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_ready : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_128_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_128_out_ap_vld : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_4_GOST_Crypt_Step_fu_587_p_din1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_4_GOST_Crypt_Step_fu_587_p_din2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_4_GOST_Crypt_Step_fu_587_p_din3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_start : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_done : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_idle : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_ready : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_Data_prep_5_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_Data_prep_5_out_ap_vld : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_start : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_done : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_idle : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_ready : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_Data_prep_6_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_Data_prep_6_out_ap_vld : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_GOST_Crypt_Step_fu_193_ap_ready : STD_LOGIC;
    signal grp_GOST_Crypt_Step_fu_193_Data_prep_read : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_GOST_Crypt_Step_fu_193_p_read1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_GOST_Crypt_Step_fu_193_Last : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_start : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_done : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_idle : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_ready : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_Data_prep_229_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_Data_prep_229_out_ap_vld : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_start : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_done : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_idle : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_ready : STD_LOGIC;
    signal grp_GOST_Encrypt_SR_Pipeline_7_fu_208_Data : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_7_fu_208_Data_ap_vld : STD_LOGIC;
    signal Data_prep_4_GOST_Crypt_Step_fu_587_ap_ready : STD_LOGIC;
    signal Data_prep_4_GOST_Crypt_Step_fu_587_ap_return : STD_LOGIC_VECTOR (63 downto 0);
    signal Data_prep_7_reg_148 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal Size_assign_fu_96 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln189_fu_383_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_236_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal icmp_ln169_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln169_fu_252_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_s_fu_302_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_5_fu_322_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_6_fu_332_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_4_fu_312_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_fu_268_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_1_fu_282_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_2_fu_292_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_3_fu_272_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln188_fu_380_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_10_fu_431_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_12_fu_451_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_13_fu_461_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_11_fu_441_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_108_fu_397_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_9_fu_411_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_7_fu_421_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_8_fu_401_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        Cur_Part_Size : IN STD_LOGIC_VECTOR (3 downto 0);
        Data_load_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        p_out_ap_vld : OUT STD_LOGIC );
    end component;


    component GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        Data_prep : IN STD_LOGIC_VECTOR (63 downto 0);
        GOST_Table_load : IN STD_LOGIC_VECTOR (7 downto 0);
        Data_prep_330_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        Data_prep_330_out_ap_vld : OUT STD_LOGIC;
        grp_GOST_Crypt_Step_fu_193_p_din1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        grp_GOST_Crypt_Step_fu_193_p_din2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        grp_GOST_Crypt_Step_fu_193_p_din3 : OUT STD_LOGIC_VECTOR (0 downto 0);
        grp_GOST_Crypt_Step_fu_193_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
        grp_GOST_Crypt_Step_fu_193_p_ready : IN STD_LOGIC );
    end component;


    component GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        Data_prep : IN STD_LOGIC_VECTOR (63 downto 0);
        GOST_Table_load : IN STD_LOGIC_VECTOR (7 downto 0);
        Data_prep_128_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        Data_prep_128_out_ap_vld : OUT STD_LOGIC;
        Data_prep_4_GOST_Crypt_Step_fu_587_p_din1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        Data_prep_4_GOST_Crypt_Step_fu_587_p_din2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        Data_prep_4_GOST_Crypt_Step_fu_587_p_din3 : OUT STD_LOGIC_VECTOR (0 downto 0);
        Data_prep_4_GOST_Crypt_Step_fu_587_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
        Data_prep_4_GOST_Crypt_Step_fu_587_p_ready : IN STD_LOGIC );
    end component;


    component GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        Data_prep_330_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        GOST_Table_load : IN STD_LOGIC_VECTOR (7 downto 0);
        Data_prep_5_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        Data_prep_5_out_ap_vld : OUT STD_LOGIC;
        grp_GOST_Crypt_Step_fu_193_p_din1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        grp_GOST_Crypt_Step_fu_193_p_din2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        grp_GOST_Crypt_Step_fu_193_p_din3 : OUT STD_LOGIC_VECTOR (0 downto 0);
        grp_GOST_Crypt_Step_fu_193_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
        grp_GOST_Crypt_Step_fu_193_p_ready : IN STD_LOGIC );
    end component;


    component GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        Data_prep_5_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        GOST_Table_load : IN STD_LOGIC_VECTOR (7 downto 0);
        Data_prep_6_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        Data_prep_6_out_ap_vld : OUT STD_LOGIC;
        grp_GOST_Crypt_Step_fu_193_p_din1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        grp_GOST_Crypt_Step_fu_193_p_din2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        grp_GOST_Crypt_Step_fu_193_p_din3 : OUT STD_LOGIC_VECTOR (0 downto 0);
        grp_GOST_Crypt_Step_fu_193_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
        grp_GOST_Crypt_Step_fu_193_p_ready : IN STD_LOGIC );
    end component;


    component GOST_Encrypt_SR_GOST_Crypt_Step IS
    port (
        ap_ready : OUT STD_LOGIC;
        Data_prep_read : IN STD_LOGIC_VECTOR (63 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
        Last : IN STD_LOGIC_VECTOR (0 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        Data_prep_128_reload : IN STD_LOGIC_VECTOR (63 downto 0);
        GOST_Table_load : IN STD_LOGIC_VECTOR (7 downto 0);
        Data_prep_229_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        Data_prep_229_out_ap_vld : OUT STD_LOGIC;
        grp_GOST_Crypt_Step_fu_193_p_din1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        grp_GOST_Crypt_Step_fu_193_p_din2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        grp_GOST_Crypt_Step_fu_193_p_din3 : OUT STD_LOGIC_VECTOR (0 downto 0);
        grp_GOST_Crypt_Step_fu_193_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
        grp_GOST_Crypt_Step_fu_193_p_ready : IN STD_LOGIC );
    end component;


    component GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_7 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        Cur_Part_Size : IN STD_LOGIC_VECTOR (3 downto 0);
        Data_prep_3 : IN STD_LOGIC_VECTOR (63 downto 0);
        Data : OUT STD_LOGIC_VECTOR (7 downto 0);
        Data_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_GOST_Encrypt_SR_Pipeline_1_fu_157 : component GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_start,
        ap_done => grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_done,
        ap_idle => grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_idle,
        ap_ready => grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_ready,
        Cur_Part_Size => Cur_Part_Size_reg_555,
        Data_load_cast => Data_i,
        p_out => grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out,
        p_out_ap_vld => grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out_ap_vld);

    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165 : component GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_start,
        ap_done => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_done,
        ap_idle => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_idle,
        ap_ready => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_ready,
        Data_prep => Data_prep_reg_567,
        GOST_Table_load => GOST_Table,
        Data_prep_330_out => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_Data_prep_330_out,
        Data_prep_330_out_ap_vld => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_Data_prep_330_out_ap_vld,
        grp_GOST_Crypt_Step_fu_193_p_din1 => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din1,
        grp_GOST_Crypt_Step_fu_193_p_din2 => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din2,
        grp_GOST_Crypt_Step_fu_193_p_din3 => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din3,
        grp_GOST_Crypt_Step_fu_193_p_dout0 => grp_GOST_Crypt_Step_fu_193_ap_return,
        grp_GOST_Crypt_Step_fu_193_p_ready => grp_GOST_Crypt_Step_fu_193_ap_ready);

    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172 : component GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_start,
        ap_done => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_done,
        ap_idle => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_idle,
        ap_ready => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_ready,
        Data_prep => Data_prep_reg_567,
        GOST_Table_load => GOST_Table,
        Data_prep_128_out => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_128_out,
        Data_prep_128_out_ap_vld => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_128_out_ap_vld,
        Data_prep_4_GOST_Crypt_Step_fu_587_p_din1 => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_4_GOST_Crypt_Step_fu_587_p_din1,
        Data_prep_4_GOST_Crypt_Step_fu_587_p_din2 => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_4_GOST_Crypt_Step_fu_587_p_din2,
        Data_prep_4_GOST_Crypt_Step_fu_587_p_din3 => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_4_GOST_Crypt_Step_fu_587_p_din3,
        Data_prep_4_GOST_Crypt_Step_fu_587_p_dout0 => Data_prep_4_GOST_Crypt_Step_fu_587_ap_return,
        Data_prep_4_GOST_Crypt_Step_fu_587_p_ready => Data_prep_4_GOST_Crypt_Step_fu_587_ap_ready);

    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179 : component GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_start,
        ap_done => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_done,
        ap_idle => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_idle,
        ap_ready => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_ready,
        Data_prep_330_reload => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_Data_prep_330_out,
        GOST_Table_load => GOST_Table,
        Data_prep_5_out => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_Data_prep_5_out,
        Data_prep_5_out_ap_vld => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_Data_prep_5_out_ap_vld,
        grp_GOST_Crypt_Step_fu_193_p_din1 => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din1,
        grp_GOST_Crypt_Step_fu_193_p_din2 => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din2,
        grp_GOST_Crypt_Step_fu_193_p_din3 => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din3,
        grp_GOST_Crypt_Step_fu_193_p_dout0 => grp_GOST_Crypt_Step_fu_193_ap_return,
        grp_GOST_Crypt_Step_fu_193_p_ready => grp_GOST_Crypt_Step_fu_193_ap_ready);

    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186 : component GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_start,
        ap_done => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_done,
        ap_idle => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_idle,
        ap_ready => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_ready,
        Data_prep_5_reload => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_Data_prep_5_out,
        GOST_Table_load => GOST_Table,
        Data_prep_6_out => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_Data_prep_6_out,
        Data_prep_6_out_ap_vld => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_Data_prep_6_out_ap_vld,
        grp_GOST_Crypt_Step_fu_193_p_din1 => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din1,
        grp_GOST_Crypt_Step_fu_193_p_din2 => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din2,
        grp_GOST_Crypt_Step_fu_193_p_din3 => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din3,
        grp_GOST_Crypt_Step_fu_193_p_dout0 => grp_GOST_Crypt_Step_fu_193_ap_return,
        grp_GOST_Crypt_Step_fu_193_p_ready => grp_GOST_Crypt_Step_fu_193_ap_ready);

    grp_GOST_Crypt_Step_fu_193 : component GOST_Encrypt_SR_GOST_Crypt_Step
    port map (
        ap_ready => grp_GOST_Crypt_Step_fu_193_ap_ready,
        Data_prep_read => grp_GOST_Crypt_Step_fu_193_Data_prep_read,
        p_read1 => grp_GOST_Crypt_Step_fu_193_p_read1,
        Last => grp_GOST_Crypt_Step_fu_193_Last,
        ap_return => grp_GOST_Crypt_Step_fu_193_ap_return);

    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201 : component GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_start,
        ap_done => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_done,
        ap_idle => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_idle,
        ap_ready => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_ready,
        Data_prep_128_reload => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_128_out,
        GOST_Table_load => GOST_Table,
        Data_prep_229_out => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_Data_prep_229_out,
        Data_prep_229_out_ap_vld => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_Data_prep_229_out_ap_vld,
        grp_GOST_Crypt_Step_fu_193_p_din1 => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din1,
        grp_GOST_Crypt_Step_fu_193_p_din2 => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din2,
        grp_GOST_Crypt_Step_fu_193_p_din3 => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din3,
        grp_GOST_Crypt_Step_fu_193_p_dout0 => grp_GOST_Crypt_Step_fu_193_ap_return,
        grp_GOST_Crypt_Step_fu_193_p_ready => grp_GOST_Crypt_Step_fu_193_ap_ready);

    grp_GOST_Encrypt_SR_Pipeline_7_fu_208 : component GOST_Encrypt_SR_GOST_Encrypt_SR_Pipeline_7
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_start,
        ap_done => grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_done,
        ap_idle => grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_idle,
        ap_ready => grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_ready,
        Cur_Part_Size => Cur_Part_Size_reg_555,
        Data_prep_3 => Data_prep_3_reg_582,
        Data => grp_GOST_Encrypt_SR_Pipeline_7_fu_208_Data,
        Data_ap_vld => grp_GOST_Encrypt_SR_Pipeline_7_fu_208_Data_ap_vld);

    Data_prep_4_GOST_Crypt_Step_fu_587 : component GOST_Encrypt_SR_GOST_Crypt_Step
    port map (
        ap_ready => Data_prep_4_GOST_Crypt_Step_fu_587_ap_ready,
        Data_prep_read => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_4_GOST_Crypt_Step_fu_587_p_din1,
        p_read1 => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_4_GOST_Crypt_Step_fu_587_p_din2,
        Last => grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_Data_prep_4_GOST_Crypt_Step_fu_587_p_din3,
        ap_return => Data_prep_4_GOST_Crypt_Step_fu_587_ap_return);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln167_fu_230_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_ready = ap_const_logic_1)) then 
                    grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                    grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_ready = ap_const_logic_1)) then 
                    grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_ready = ap_const_logic_1)) then 
                    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_lv1_1 = Mode_read_read_fu_124_p2) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_ready = ap_const_logic_1)) then 
                    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
                    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_ready = ap_const_logic_1)) then 
                    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_lv1_0 = Mode_read_read_fu_124_p2) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_ready = ap_const_logic_1)) then 
                    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_ready = ap_const_logic_1)) then 
                    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    Size_assign_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                Size_assign_fu_96 <= Size;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                Size_assign_fu_96 <= sub_ln189_fu_383_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln167_fu_230_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                Cur_Part_Size_reg_555 <= Cur_Part_Size_fu_256_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
                Data_prep_3_reg_582 <= Data_prep_3_fu_471_p9;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_lv1_1 = Mode_read_read_fu_124_p2) and (ap_const_logic_1 = ap_CS_fsm_state10)) or ((ap_const_lv1_0 = Mode_read_read_fu_124_p2) and (ap_const_logic_1 = ap_CS_fsm_state10)))) then
                Data_prep_7_reg_148 <= grp_GOST_Crypt_Step_fu_193_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                Data_prep_reg_567 <= Data_prep_fu_342_p9;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, Mode_read_read_fu_124_p2, ap_CS_fsm_state2, icmp_ln167_fu_230_p2, ap_CS_fsm_state4, grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_done, grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_done, grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_done, grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_done, grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_done, grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_done, grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state11, ap_CS_fsm_state7, ap_CS_fsm_state9, ap_CS_fsm_state13, ap_CS_fsm_state17)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln167_fu_230_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_lv1_1 = Mode_read_read_fu_124_p2) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state11 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state11) and (grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state13) and (grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state17) and (grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state17;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXX";
        end case;
    end process;
    Cur_Part_Size_fu_256_p3 <= 
        trunc_ln169_fu_252_p1 when (icmp_ln169_fu_246_p2(0) = '1') else 
        ap_const_lv4_8;

    Data_o_assign_proc : process(Data_i, grp_GOST_Encrypt_SR_Pipeline_7_fu_208_Data, grp_GOST_Encrypt_SR_Pipeline_7_fu_208_Data_ap_vld, ap_CS_fsm_state17)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state17) and (grp_GOST_Encrypt_SR_Pipeline_7_fu_208_Data_ap_vld = ap_const_logic_1))) then 
            Data_o <= grp_GOST_Encrypt_SR_Pipeline_7_fu_208_Data;
        else 
            Data_o <= Data_i;
        end if; 
    end process;


    Data_o_ap_vld_assign_proc : process(grp_GOST_Encrypt_SR_Pipeline_7_fu_208_Data_ap_vld, ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            Data_o_ap_vld <= grp_GOST_Encrypt_SR_Pipeline_7_fu_208_Data_ap_vld;
        else 
            Data_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    Data_prep_3_fu_471_p9 <= (((((((p_10_fu_431_p4 & p_12_fu_451_p4) & p_13_fu_461_p4) & p_11_fu_441_p4) & empty_108_fu_397_p1) & p_9_fu_411_p4) & p_7_fu_421_p4) & p_8_fu_401_p4);
    Data_prep_fu_342_p9 <= (((((((p_s_fu_302_p4 & p_5_fu_322_p4) & p_6_fu_332_p4) & p_4_fu_312_p4) & empty_fu_268_p1) & p_1_fu_282_p4) & p_2_fu_292_p4) & p_3_fu_272_p4);
    Mode_read_read_fu_124_p2 <= (0=>Mode, others=>'-');
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state11_blk_assign_proc : process(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_done)
    begin
        if ((grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state12_blk <= ap_const_logic_0;

    ap_ST_fsm_state13_blk_assign_proc : process(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_done)
    begin
        if ((grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state13_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state13_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;

    ap_ST_fsm_state17_blk_assign_proc : process(grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_done)
    begin
        if ((grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state17_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state17_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_done)
    begin
        if ((grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_done)
    begin
        if ((grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_done)
    begin
        if ((grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_done)
    begin
        if ((grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state2, icmp_ln167_fu_230_p2)
    begin
        if (((icmp_ln167_fu_230_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln167_fu_230_p2)
    begin
        if (((icmp_ln167_fu_230_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    empty_108_fu_397_p1 <= Data_prep_7_reg_148(8 - 1 downto 0);
    empty_fu_268_p1 <= grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out(8 - 1 downto 0);

    grp_GOST_Crypt_Step_fu_193_Data_prep_read_assign_proc : process(ap_CS_fsm_state10, Mode_read_read_fu_124_p2, ap_CS_fsm_state4, grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din1, grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din1, grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_Data_prep_6_out, grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din1, grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_Data_prep_229_out, grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din1, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state12, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            grp_GOST_Crypt_Step_fu_193_Data_prep_read <= grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            grp_GOST_Crypt_Step_fu_193_Data_prep_read <= grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            grp_GOST_Crypt_Step_fu_193_Data_prep_read <= grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            grp_GOST_Crypt_Step_fu_193_Data_prep_read <= grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din1;
        elsif (((ap_const_lv1_1 = Mode_read_read_fu_124_p2) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            grp_GOST_Crypt_Step_fu_193_Data_prep_read <= grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_Data_prep_229_out;
        elsif (((ap_const_lv1_0 = Mode_read_read_fu_124_p2) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            grp_GOST_Crypt_Step_fu_193_Data_prep_read <= grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_Data_prep_6_out;
        else 
            grp_GOST_Crypt_Step_fu_193_Data_prep_read <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_GOST_Crypt_Step_fu_193_Last_assign_proc : process(ap_CS_fsm_state10, Mode_read_read_fu_124_p2, ap_CS_fsm_state4, grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din3, grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din3, grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din3, grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din3, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state12, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            grp_GOST_Crypt_Step_fu_193_Last <= grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            grp_GOST_Crypt_Step_fu_193_Last <= grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            grp_GOST_Crypt_Step_fu_193_Last <= grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            grp_GOST_Crypt_Step_fu_193_Last <= grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din3;
        elsif ((((ap_const_lv1_1 = Mode_read_read_fu_124_p2) and (ap_const_logic_1 = ap_CS_fsm_state10)) or ((ap_const_lv1_0 = Mode_read_read_fu_124_p2) and (ap_const_logic_1 = ap_CS_fsm_state10)))) then 
            grp_GOST_Crypt_Step_fu_193_Last <= ap_const_lv1_1;
        else 
            grp_GOST_Crypt_Step_fu_193_Last <= "X";
        end if; 
    end process;


    grp_GOST_Crypt_Step_fu_193_p_read1_assign_proc : process(GOST_Table, ap_CS_fsm_state10, Mode_read_read_fu_124_p2, ap_CS_fsm_state4, grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din2, grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din2, grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din2, grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din2, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state12, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            grp_GOST_Crypt_Step_fu_193_p_read1 <= grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_grp_GOST_Crypt_Step_fu_193_p_din2;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            grp_GOST_Crypt_Step_fu_193_p_read1 <= grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_grp_GOST_Crypt_Step_fu_193_p_din2;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            grp_GOST_Crypt_Step_fu_193_p_read1 <= grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_grp_GOST_Crypt_Step_fu_193_p_din2;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            grp_GOST_Crypt_Step_fu_193_p_read1 <= grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_grp_GOST_Crypt_Step_fu_193_p_din2;
        elsif ((((ap_const_lv1_1 = Mode_read_read_fu_124_p2) and (ap_const_logic_1 = ap_CS_fsm_state10)) or ((ap_const_lv1_0 = Mode_read_read_fu_124_p2) and (ap_const_logic_1 = ap_CS_fsm_state10)))) then 
            grp_GOST_Crypt_Step_fu_193_p_read1 <= GOST_Table;
        else 
            grp_GOST_Crypt_Step_fu_193_p_read1 <= "XXXXXXXX";
        end if; 
    end process;

    grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_start <= grp_GOST_Encrypt_SR_Pipeline_1_fu_157_ap_start_reg;
    grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_start <= grp_GOST_Encrypt_SR_Pipeline_7_fu_208_ap_start_reg;
    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_start <= grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_107_4_fu_186_ap_start_reg;
    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_start <= grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_65_1_VITIS_LOOP_67_2_fu_172_ap_start_reg;
    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_start <= grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_77_3_fu_201_ap_start_reg;
    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_start <= grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_92_1_fu_165_ap_start_reg;
    grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_start <= grp_GOST_Encrypt_SR_Pipeline_VITIS_LOOP_98_2_VITIS_LOOP_100_3_fu_179_ap_start_reg;
    icmp_ln167_fu_230_p2 <= "1" when (Size_assign_fu_96 = ap_const_lv32_0) else "0";
    icmp_ln169_fu_246_p2 <= "1" when (tmp_fu_236_p4 = ap_const_lv29_0) else "0";
    p_10_fu_431_p4 <= Data_prep_7_reg_148(39 downto 32);
    p_11_fu_441_p4 <= Data_prep_7_reg_148(63 downto 56);
    p_12_fu_451_p4 <= Data_prep_7_reg_148(47 downto 40);
    p_13_fu_461_p4 <= Data_prep_7_reg_148(55 downto 48);
    p_1_fu_282_p4 <= grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out(15 downto 8);
    p_2_fu_292_p4 <= grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out(23 downto 16);
    p_3_fu_272_p4 <= grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out(31 downto 24);
    p_4_fu_312_p4 <= grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out(63 downto 56);
    p_5_fu_322_p4 <= grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out(47 downto 40);
    p_6_fu_332_p4 <= grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out(55 downto 48);
    p_7_fu_421_p4 <= Data_prep_7_reg_148(23 downto 16);
    p_8_fu_401_p4 <= Data_prep_7_reg_148(31 downto 24);
    p_9_fu_411_p4 <= Data_prep_7_reg_148(15 downto 8);
    p_s_fu_302_p4 <= grp_GOST_Encrypt_SR_Pipeline_1_fu_157_p_out(39 downto 32);
    sub_ln189_fu_383_p2 <= std_logic_vector(unsigned(Size_assign_fu_96) - unsigned(zext_ln188_fu_380_p1));
    tmp_fu_236_p4 <= Size_assign_fu_96(31 downto 3);
    trunc_ln169_fu_252_p1 <= Size_assign_fu_96(4 - 1 downto 0);
    zext_ln188_fu_380_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Cur_Part_Size_reg_555),32));
end behav;
